version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: "json-file"
      options: 
        max-size: "2m"
        max-file: "10"
  stt:
    container_name: app_stt
    restart: always
    image: kharatsa/strack:latest
    ports:
      - "8081:8081"
    volumes:
      - /var/log/stt/:/var/log/stt/
    environment:
      - STT_LISTEN_PORT=8081
      - STT_LISTEN_HOST=0.0.0.0
      - STT_PUBLIC_URL=https://$TL_HOSTNAME
      - ODK_PROTOCOL=http
      - ODK_HOSTNAME=odk
      - VIRTUAL_HOST=$TL_HOSTNAME
    env_file:
      - /etc/stt_creds
    logging:
      driver: "json-file"
      options: 
        max-size: "2m"
        max-file: "10"
    links:
      - odk
  odk:
    image: kharatsa/odkaggregate:latest
    container_name: odk_stt
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ODK_HOSTNAME=odk.$TL_HOSTNAME
      - ODK_PORT=8080
      - ODK_ADMIN_USERNAME=admin
      - VIRTUAL_HOST=odk.$TL_HOSTNAME
    env_file:
      - /etc/stt_creds
    logging:
      driver: "json-file"
      options: 
        max-size: "2m"
        max-file: "10"
