version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-sttdev
    ports:
      - "8081:8081"
    image: stt_dev
    container_name: app_stt
    command: gulp
    volumes:
      - stt_app:/var/lib/strack/
      - .:/var/www/strack/
      - ./log:/var/log/strack/
    depends_on:
      - db
      - odk
    links:
      - db
      - odk
    environment:
      - NODE_ENV=development
      - STT_LISTEN_PORT=8081
      - STT_LISTEN_HOST=0.0.0.0
      - STT_PUBLIC_URL="http://localhost:8081"
      - ODK_PROTOCOL=http
      - ODK_HOSTNAME=odk
      - ODK_USERNAME=stt
      - ODK_PASSWORD=password
    env_file:
      - ./docker/mysql_dev.env
  odk:
    image: kharatsa/odkaggregate:latest
    container_name: odk_stt
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    environment:
      - ODK_HOSTNAME=localhost
      - ODK_PORT=8080
      - ODK_ADMIN_USERNAME=admin
      - DB_CONTAINER_NAME=db
    env_file:
      - ./docker/mysql_dev.env
  db:
    image: mysql:5.7
    container_name: db_stt
    volumes:
      - stt_db:/var/lib/mysql/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - ./docker/mysql_dev.env
volumes:
  stt_db:
  stt_app:
