version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  server:
    container_name: app_stt
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server-dev
    ports:
      - "8081:8081"
    volumes:
      - stt_data:/var/lib/stt/
      - ./:/var/www/stt/
      - ./log/:/var/log/stt/
      - /var/www/stt/node_modules
    depends_on:
      - odk
    links:
      - odk
    environment:
      - NODE_ENV=development
      - STT_LISTEN_PORT=8081
      - STT_LISTEN_HOST=0.0.0.0
      - STT_PUBLIC_URL="http://localhost:8081"
      - ODK_PROTOCOL=http
      - ODK_HOSTNAME=odk
      - ODK_USERNAME=stt
      - ODK_PASSWORD=password
      - VIRTUAL_HOST=app.bar.com
    env_file:
      - ./docker/env-prod.env
  odk:
    image: kharatsa/odkaggregate:latest
    container_name: odk_stt
    ports:
      - "8080:8080"
    environment:
      - ODK_HOSTNAME=localhost
      - ODK_PORT=8080
      - ODK_ADMIN_USERNAME=admin
      - VIRTUAL_HOST=odk.bar.com
    env_file:
      - ./docker/env-prod.env
volumes:
  stt_data:
