version: '2'
services:
  bundler:
    container_name: bundler_stt
    image: kharatsa/strack
    command: gulp
    volumes:
      - ./:/var/www/stt/
      - /var/www/stt/node_modules/
      - /var/www/stt/bower_components/
    environment:
      - NODE_ENV=development
  server:
    container_name: app_stt
    image: kharatsa/strack
    command: node_modules/.bin/nodemon app/server
    ports:
      - "8081:8081"
    volumes:
      - ./:/var/www/stt/
      - ./log/:/var/log/stt/
      - stt_data:/var/lib/stt/
      - /var/www/stt/node_modules/
    env_file: ./dev/stt_dev.env
    environment:
      - NODE_ENV
      - ODK_HOSTNAME=odk
      - STT_DB_HOST=db
    depends_on:
      - db
      - odk
    links:
      - db
      - odk
  odk:
    image: kharatsa/odkaggregate:latest
    container_name: odk_stt
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    environment:
      - ODK_HOSTNAME=localhost
      - ODK_PORT=8080
      - ODK_ADMIN_USERNAME=admin
      - MYSQL_HOSTNAME=db
    env_file: ./dev/mysql_dev.env
  db:
    build:
      context: .
      dockerfile: ./dev/Dockerfile-mysql-dev
    container_name: db_stt
    volumes:
      - db_data:/var/lib/mysql/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - ./dev/mysql_dev.env
volumes:
  db_data:
  stt_data:
