FROM nginx:stable

COPY ./deploy/nginx/letsencrypt.template \
  ./deploy/nginx/stt.template \
  ./deploy/nginx/odk.template \
  ./deploy/nginx/proxy.conf \
  /etc/nginx/conf.d/
COPY ./deploy/nginx/start_nginx.sh /root/

RUN chmod +x /root/start_nginx.sh

CMD /root/start_nginx.sh
