FROM nginx:stable

COPY ./letsencrypt.template \
  ./stt.template \
  ./odk.template \
  ./proxy.conf \
  /etc/nginx/conf.d/
COPY ./start_nginx.sh /root/

RUN chmod +x /root/start_nginx.sh

CMD /root/start_nginx.sh
