version: '2'
services:
  stt:
    image: kharatsa/strack:latest
    container_name: app_stt
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /var/log/stt/:/var/log/stt/
      - /usr/share/nginx/html/:/var/www/stt/app/public/
    env_file:
      - /etc/stt_creds
    environment:
      - STT_LISTEN_PORT=8081
      - STT_LISTEN_HOST=0.0.0.0
      - STT_PUBLIC_URL=https://$TL_HOSTNAME
      - ODK_PROTOCOL=http
      - ODK_HOSTNAME=odk
    logging:
      driver: "json-file"
      options: 
        max-size: "2m"
        max-file: "10"
    links:
      - odk
  odk:
    image: kharatsa/odkaggregate:latest
    container_name: odk_stt
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - /etc/stt_creds
    environment:
      - ODK_HOSTNAME=odk.$TL_HOSTNAME
      - ODK_PORT=8080
      - ODK_ADMIN_USERNAME=admin
    logging:
      driver: "json-file"
      options: 
        max-size: "2m"
        max-file: "10"
volumes:
  static:
