FROM quay.io/letsencrypt/letsencrypt:latest
MAINTAINER Sean Herman <sjh293@cornell.edu>

RUN apt-get update \
  && apt-get install gettext -yq --no-install-recommends \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY /deploy/certbot_cron ./deploy/certbot_conf.template /root/
RUN cp /root/certbot_cron /etc/cron.d/certbot_cron \
  && chmod 0644 /etc/cron.d/certbot_cron \
  && touch /var/log/cron.log

ENTRYPOINT []
CMD bash -c "envsubst < /root/certbot_conf.template > /root/certbot_conf.ini && cron && tail -F /var/log/cron.log"
